// Generated by https://quicktype.io

export interface MatchesResponse {
    count: number;
    data:  Match[];
}

export interface Match {
    name_2:    string;
    name_1:    string;
    winner:    string;
    extra:     string;
    champ_2:   string;
    champ_1:   string;
    picture_2: string;
    picture_1: string;
    ts:        string;
}

export interface Form {
    name_2?:    string;
    name_1?:    string;
    winner?:    string;
    extra?:     string;
    champ_2?:   string;
    champ_1?:   string;
    picture_2?: string;
    picture_1?: string;
    ts?:        string;
}
